[package]
name = "js_executor"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
argus_models = { path = "../argus_models" }
deno_core = "0.360.0"
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
