[package]
name = "argus"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.23", features = ["essentials"] }
async-trait = "0.1.88"
config = { version = "0.15.13", features = ["yaml"] }
dashmap = { version = "6.1.0", features = ["serde"] }
futures = "0.3.31"
hex = "0.4.3"
rhai = { version = "1.22.2", features = ["sync"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
sqlx = { version = "0.8.6", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "macros",
  "migrate",
] }
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["full"] }
tower = { version = "0.5.2", features = ["retry"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.2"
