[package]
name = "argus-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.0.23"
async-trait = "0.1.88"
config = "0.15.13"
serde = "1.0.219"
serde_json = "1.0.141"
sqlx = "0.8.6"
thiserror = "2.0.12"
tokio = "1.47.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
