database_url: "sqlite:data/monitor.db"
rpc_urls:
  - "https://1rpc.io/eth"
  - "https://rpc.mevblocker.io"
  - "https://eth.llamarpc.com"
network_id: "ethereum"

# Controls where Argus starts on a fresh database.
# Can be a block number, 'latest', or a negative offset from the head.
initial_start_block: -100 

block_chunk_size: 5
polling_interval_ms: 10000
confirmation_blocks: 12
notification_channel_capacity: 1024
abi_config_path: abis/

# Optional: Configuration for the RPC retry policy.
# If this section is omitted, default values will be used.
retry_config:
  # The maximum number of retries for a request.
  max_retry: 10
  # The initial backoff delay in milliseconds.
  backoff_ms: 1000
  # The number of compute units per second to allow (for rate limiting).
  compute_units_per_second: 100

# Optional: Configuration for graceful shutdown timeout.
# If this section is omitted, the default value of 30 seconds will be used.
shutdown_timeout_secs: 30

# API server configuration
api_server_listen_address: "0.0.0.0:8080"
