# This is an example configuration file for defining monitors.
# You can copy this file to `monitors.yaml` and update `config.yaml` to point to it.
monitors:
  - name: "Large ETH Transfers (Ethereum)"
    network: "ethereum"
    filter_script: |
      tx.value > ether("10")
    notifiers:
      - "telegram big transfer"
