name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'sqlite://data/data.db'

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the Rust toolchain
      - name: Set up Rust nightly
        run: |
          rustup default nightly
          rustup component add clippy rustfmt

      # Check code formatting with rustfmt
      - name: Check code formatting
        run: cargo fmt -- --check

      # Run cargo check to verify the project compiles
      - name: Run cargo check
        env:
          SQLX_OFFLINE: '1'
        run: cargo check --workspace

      # Run clippy to catch lints and warnings (treat warnings as errors)
      - name: Run cargo clippy
        env:
          SQLX_OFFLINE: '1'
        run: cargo clippy --workspace -- -D warnings

      # Run tests
      - name: Run tests
        env:
          SQLX_OFFLINE: '1'
        run: cargo test --workspace



  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo-tarpaulin
        id: cache-cargo-tarpaulin
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-cargo-tarpaulin
          restore-keys: |
            ${{ runner.os }}-cargo-tarpaulin

      - name: Install cargo-tarpaulin
        if: steps.cache-cargo-tarpaulin.outputs.cache-hit != 'true'
        run: cargo install cargo-tarpaulin

      - name: Run tests with coverage
        run: cargo tarpaulin --workspace --ignored --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
          fail_ci_if_error: true
