name: Security

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run security audit
        run: cargo install cargo-audit && cargo audit
